# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_auto_20171124_1609'),
        ('contacts', '0069_iso639-3'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSecondaryOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_org', to='contacts.Contact')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_secondary_org', to='orgs.Org')),
            ],
        ),
    ]
