# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0002_migrationrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='channels',
            field=models.TextField(null=True, verbose_name='Channels'),
        ),
    ]
